name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: bauhausphp/contributor-tool

    - name: Setup
      run: |
        BRANCH=$(echo ${GITHUB_REF} | cut -d '/' -f 3-)
        make setup package=message-bus branch=${BRANCH}

    - name: Tests
      run: make tests package=message-bus

    - name: Coverage
      run: |
        printenv | grep COVERALLS_REPO_TOKEN > docker/run.env
        make coverage package=message-bus
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
